blueprint:
  name: Linked Entities
  description: >
    🔛 Linked Entities
        version: 1.0

    This blueprint allows you to easily create/maintain an automation that links the state of multiple entities:
      - When you turn ANY linked entity ON, it will turn ON ALL linked entities.
      - When you turn ANY linked entity OFF, it will turn OFF ALL linked entities.

    NOTE: You can select any entity with an ON/OFF state (switches, lights, etc.)

    My main use-case was for multiple light switches in the house controlling the same light, but I also use it for other things:
    - at dawn, when I turn on the external lights (a shelly switch), I also link the pool light mqtt switch.
    - when I want to open the external gate, I can use several linked switches in 2-3 rooms of the house
    - when I want to manually turn on/off the irrigation system, I use two switches (internal and external) to activate my RainMachine cycle

    I'm sure you'll find many more examples. :slight_smile:

    If you like to show your support please hit the star button and click here: https://www.paypal.com/donate/?hosted_button_id=8V9YE6S5E869G

    - Import in HA: https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fraw.githubusercontent.com%2Falexdelprete%2Fha-blueprints%2Fmain%2Fha-blueprint-linked-entities.yaml
    - Source: https://github.com/alexdelprete/ha-blueprints
    - Support: https://community.home-assistant.io/t/linked-entities-keep-mutlple-entities-binary-state-in-sync-lights-switches-etc/662836?u=alexdelprete

  domain: automation
  input:
    linked_entity:
      name: Linked Entity *
      description: Entities whose state will be linked (if any of them transitions to ON state, all will be ON, and the same for the OFF state).
      selector:
        entity:
          multiple: true

variables:
  linked_entity: !input linked_entity

trigger:
  - platform: state
    id: turn_on
    entity_id: !input linked_entity
    from: "off"
    to: "on"
    for:
      milliseconds: 100
  - platform: state
    id: turn_off
    entity_id: !input linked_entity
    from: "on"
    to: "off"
    for:
      milliseconds: 100

action:
  - choose:
    - alias: "An entity turned ON"
      conditions:
        - condition: trigger
          id: turn_on
      sequence:
        - alias: "Turn ON all linked entities"
          service: homeassistant.turn_on
          target:
            entity_id: !input linked_entity
    - alias: "An entity turned OFF"
      conditions:
        - condition: trigger
          id: turn_off
      sequence:
        - alias: "Turn OFF all linked entities"
          service: homeassistant.turn_off
          target:
            entity_id: !input linked_entity
