blueprint:
  name: Linked Entities
  description: >
    # 🔛 Linked Entities

    **Version: 1.0**

    This automation allows to link the state of multiple entities.

    **The Automation Process:**
      - When you turn ANY linked entity ON, it will turn ON ALL linked entities.
      - When you turn ANY linked entity OFF, it will turn OFF ALL linked entities.

    **NOTE** - You can select any entity with an ON/OFF state (switches, lights, etc.)

    Need help? See our FAQ: [Click Here](https://community.home-assistant.io/t/)
    **If you like to show your support hit the like button and** [Click Here](https://www.paypal.com/donate/?hosted_button_id=8V9YE6S5E869G) 🙂
  domain: automation
  input:
    linked_entity:
      name: Linked Entity *
      description: Entities whose state will be linked (if any of them transitions to ON state, all will be ON, and the same for the OFF state).
      selector:
        entity:
          multiple: true

variables:
  linked_entity: !input linked_entity

trigger:
  - platform: state
    id: turn_on
    entity_id: !input linked_entity
    from: "off"
    to: "on"
    for:
      milliseconds: 100
  - platform: state
    id: turn_off
    entity_id: !input linked_entity
    from: "on"
    to: "off"
    for:
      milliseconds: 100

action:
  - choose:
    - alias: "An entity turned ON"
      conditions:
        - condition: trigger
          id: turn_on
      sequence:
        - alias: "Turn ON all linked entities"
          service: homeassistant.turn_on
          target:
            entity_id: !input linked_entity
    - alias: "An entity turned OFF"
      conditions:
        - condition: trigger
          id: turn_off
      sequence:
        - alias: "Turn OFF all linked entities"
          service: homeassistant.turn_off
          target:
            entity_id: !input linked_entity
